class Evento { constructor({id=crypto.randomUUID(),nome,local,data,hora,categoria,vagas,descricao,imagem=''}){Object.assign(this,{id,nome,local,data,hora,categoria,vagas:Number(vagas),descricao,imagem})} }
const eventParticipants = id => state.participants.filter(p=>p.eventId===id);
const eventStatus = e => { const free=e.vagas-eventParticipants(e.id).length; return free<=0?'lotado':free<=Math.max(2,Math.ceil(e.vagas*.2))?'ultimas':'disponivel' };
const adicionarEvento = payload => { const normalized=payload.nome.trim().toLowerCase(); if(state.events.some(e=>e.nome.toLowerCase()===normalized)) throw Error('Já existe uma experiência com esse nome.'); const event=new Evento(payload); state.events.push(event); notify(`Nova órbita: ${event.nome}`, '✦'); persist(); return event };
const editarEvento = payload => { const i=state.events.findIndex(e=>e.id===payload.id); if(i<0) throw Error('Evento não encontrado.'); if(state.events.some(e=>e.id!==payload.id&&e.nome.toLowerCase()===payload.nome.trim().toLowerCase())) throw Error('Esse nome já está em uso.'); state.events[i]=new Evento(payload); persist(); return state.events[i] };
const removerEvento = id => { state.events=state.events.filter(e=>e.id!==id); state.participants=state.participants.filter(p=>p.eventId!==id); state.favorites=state.favorites.filter(f=>f!==id); notify('Uma órbita foi removida','◌');persist() };
const listarEventos=()=>state.events; const buscarEvento=q=>state.events.filter(e=>`${e.nome} ${e.categoria} ${e.local}`.toLowerCase().includes(q.toLowerCase()));
const ordenarEventos=(events,by)=>[...events].sort((a,b)=>by==='name'?a.nome.localeCompare(b.nome):by==='participants'?eventParticipants(b.id).length-eventParticipants(a.id).length:by==='capacity'?b.vagas-a.vagas:`${a.data}${a.hora}`.localeCompare(`${b.data}${b.hora}`));
const filtrarEventos=(events,{category,status,month})=>events.filter(e=>(!category||e.categoria===category)&&(!status||eventStatus(e)===status)&&(!month||e.data.slice(5,7)===month));
